/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PantallaReportesCold.java
 *
 * Created on 07/10/2011, 17:40:16
 */

package crm.gui.cold;

import crm.client.managers.PresupuestosManager;
import crm.client.report.ReportBuilder;
import crm.client.util.ProgressDialogUtil;
import crm.client.util.Util;
import crm.gui.Main;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.net.URL;
import java.rmi.RemoteException;
import java.util.Calendar;
import java.util.GregorianCalendar;
import javax.swing.event.ChangeEvent;
import javax.swing.event.ChangeListener;
import org.apache.commons.lang.StringUtils;

/**
 *
 * @author saciar
 */
public class PantallaReportesCold extends javax.swing.JDialog {

    /** Creates new form PantallaReportesCold */
    public PantallaReportesCold(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        updatePosition();
        createListeners();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jLabel1 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        diaryButton = new javax.swing.JRadioButton();
        jLabel2 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        fecha = new crm.gui.components.JXDatePicker();
        jSeparator2 = new javax.swing.JSeparator();
        osButton = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        nroOrden = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        jPanel1 = new javax.swing.JPanel();
        viewReport = new javax.swing.JButton();
        exit = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Buscador de reportes del Cold");

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 18));
        jLabel1.setText("Reportes");

        buttonGroup1.add(diaryButton);
        diaryButton.setSelected(true);
        diaryButton.setText("Diary Planner");

        jLabel2.setText("Seleccione la unidad a filtrar");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Todas", "Baires","Rural", "MDQ" }));

        jLabel3.setText("Seleccione la fecha a ver");

        buttonGroup1.add(osButton);
        osButton.setText("Orden de servicio");

        jLabel4.setText("Ingrese el numero de orden");

        viewReport.setText("Buscar");
        viewReport.setIcon(new javax.swing.ImageIcon(getUrlImagen("magnifier.png")));
        jPanel1.add(viewReport);

        exit.setText("Salir");
        exit.setIcon(new javax.swing.ImageIcon(getUrlImagen("cross.png")));
        jPanel1.add(exit);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(10, 10, 10)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(21, 21, 21)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel3)
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                            .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabel2)
                                            .addGap(4, 4, 4)
                                            .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addComponent(diaryButton)))
                        .addComponent(jSeparator1))
                    .addComponent(jSeparator2, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(21, 21, 21)
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(nroOrden, javax.swing.GroupLayout.DEFAULT_SIZE, 186, Short.MAX_VALUE))
                            .addComponent(osButton)))
                    .addComponent(jSeparator3, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(diaryButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(fecha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(osButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(nroOrden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator3, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void createListeners() {
        exit.addActionListener(new ExitAction());
        viewReport.addActionListener(new ViewReportAction());
        osButton.addChangeListener(new OSChangeListener());
    }

    public void updatePosition() {

        Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();

        this.setLocation((screenSize.width - this.getWidth()) / 2,
                (screenSize.height - this.getHeight()) / 2);

    }

    private class ViewReportAction implements ActionListener {

        public void actionPerformed(ActionEvent arg0) {
            ProgressDialogUtil.setType(ProgressDialogUtil.LOAD_REPORT_TYPE);
            ProgressDialogUtil.launchProcessDialog(Main.getVentana());
            new Thread(new Runnable() {

                public void run() {
                    if (diaryButton.isSelected()) {
                        Calendar c = new GregorianCalendar();
                        c.setTime(fecha.getDate());
                        int dia = c.get(Calendar.DATE);
                        int mes = c.get(Calendar.MONTH) + 1;
                        int anio = c.get(Calendar.YEAR);
                        ReportBuilder.previewDiaryPlannerReport(dia, mes, anio, (String)jComboBox1.getSelectedItem());
                        //dispose();
                        ProgressDialogUtil.closeProcessDialog();
                    } else if (osButton.isSelected() && !StringUtils.isBlank(nroOrden.getText())) {
                        try {
                            boolean isOS = false;
                            Object[] estado = PresupuestosManager.instance().buscarEstadoActual(Long.parseLong(nroOrden.getText()));

                            for (int j = 0; j < estado.length; j++) {
                                Object[] estados = (Object[]) estado[j];
                                if ((Integer) estados[5] == 1) {
                                    isOS = true;
                                }
                            }
                            if (isOS) {
                                ReportBuilder.previewOSReport(Long.parseLong(nroOrden.getText()));
                                //dispose();
                                ProgressDialogUtil.closeProcessDialog();
                            } else {
                                Util.errMsg(Main.getVentana(), "La orden solicitada no tiene orden de servicio seleccionado.", null);
                                ProgressDialogUtil.closeProcessDialog();
                            }
                        } catch (NumberFormatException e) {
                            Util.errMsg(Main.getVentana(), "Error, la orden debe ser un numero v�lido.", e);
                            ProgressDialogUtil.closeProcessDialog();
                        } catch (RemoteException e) {
                            Util.errMsg(Main.getVentana(), "Error al cargar datos externos.", e);
                            ProgressDialogUtil.closeProcessDialog();
                        }
                    }
                }
            }).start();
        }
    }

    private class ExitAction implements ActionListener {

        public void actionPerformed(ActionEvent arg0) {
            dispose();
        }
    }

    private class OSChangeListener implements ChangeListener {

        public void stateChanged(ChangeEvent arg0) {
            if (osButton.isSelected()) {
                nroOrden.setEnabled(true);
                fecha.setEnabled(false);
                jComboBox1.setEnabled(false);
            } else {
                nroOrden.setEnabled(false);
                fecha.setEnabled(true);
                jComboBox1.setEnabled(true);
            }

        }
    }

    public URL getUrlImagen(String imagen){

    	URL url =Main.class.getResource("imagenes/"+imagen);

    	return url;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JRadioButton diaryButton;
    private javax.swing.JButton exit;
    private crm.gui.components.JXDatePicker fecha;
    private javax.swing.JComboBox jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JTextField nroOrden;
    private javax.swing.JRadioButton osButton;
    private javax.swing.JButton viewReport;
    // End of variables declaration//GEN-END:variables

}
